name: 'Install Wine'
description: 'Installs wine on the githib action bot.'
author: 'infinitespace-studios'
runs:
  using: "composite"
  steps:
    - name: Install Wine Dependencies for MacOS
      if: runner.os == 'macOS'
      run: |
        brew install libpng libjpeg libtiff
        brew install --cask xquartz wine-stable
        xattr -dr com.apple.quarantine "/Applications/Wine Stable.app"
        wine --version
        which wine
      shell: bash
    - name: Get Ubuntu version
      if: runner.os == 'Linux' 
      id: osinfo
      run: |
        source /etc/os-release
        echo "VERSION_ID=$VERSION_ID"
        echo "version_id=$VERSION_ID" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Select Wine Source
      id: osversion
      if: runner.os == 'Linux'
      run: |
        source /etc/os-release
        if [ "$VERSION_ID" = "24.04" ]; then
          echo "winesource=noble" >> "$GITHUB_OUTPUT"
        else
          echo "winesource=jammy" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Install Wine Dependencies for Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt update
        sudo apt install p7zip-full curl
        sudo dpkg --add-architecture i386 
        sudo mkdir -pm755 /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/${{ steps.osversion.outputs.winesource }}/winehq-${{ steps.osversion.outputs.winesource }}.sources
        sudo apt update
        sudo apt-cache policy winehq-stable
        sudo apt install --install-recommends winehq-stable
        wine --version
        which wine        
      shell: bash
    - name: Install Fonts
      if: runner.os == 'Linux'
      run: |
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
        sudo apt install -y ttf-mscorefonts-installer
        sudo fc-cache
        fc-match Arial
      shell: bash
    - name: Install Dotnet in Wine
      if: runner.os != 'Windows'
      run: |
        wget -qO- https://monogame.net/downloads/net9_mgfxc_wine_setup.sh | bash
      shell: bash
    - name: Setup Environment
      if: runner.os != 'Windows'
      run: |
        echo "WINEPREFIX=$HOME/.winemonogame" >> $GITHUB_ENV
        echo "WINEARCH=win64" >> $GITHUB_ENV
        echo "WINEDEBUG=-all" >> $GITHUB_ENV
        echo "WINEDLLOVERRIDES=d3dcompiler_47=n" >> $GITHUB_ENV
      shell: bash
    - name: Reset Wine Config
      if: runner.os != 'Windows'
      run: |
        wineboot
      shell: bash
    - name: Manual Dotnet install
      if: runner.os == 'Linux'
      run: |
        DOTNET_URL="https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.104/dotnet-sdk-9.0.104-win-x64.zip"
        curl $DOTNET_URL --output "/tmp/dotnet-sdk.zip"
        cd "${{ env.WINEPREFIX }}/drive_c/windows/system32/"
        pwd
        7z x "/tmp/dotnet-sdk.zip" -y -bb1
        pwd
        ls -la
      shell: bash
