name: 'Install Wine'
description: 'Installs wine on the githib action bot.'
author: 'infinitespace-studios'
runs:
  using: "composite"
  steps:
    - name: Info
      run: pwd
      shell: bash
    - name: Install Wine Dependencies for MacOS
      if: runner.os == 'macOS'
      run: |
        brew install libpng libjpeg libtiff
        brew install --cask xquartz wine-stable
        xattr -dr com.apple.quarantine "/Applications/Wine Stable.app"
        wine --version
        which wine
      shell: bash
    - name: Get Ubuntu version
      if: runner.os == 'Linux' 
      id: osinfo
      run: |
        source /etc/os-release
        echo "VERSION_ID=$VERSION_ID"
        echo "version_id=$VERSION_ID" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Install Wine Dependencies for Ubuntu 24.04
      if: runner.os == 'Linux' && steps.osinfo.outputs.version_id == '24.04'
      run: |
        sudo apt clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt update
        sudo apt install p7zip-full curl
        sudo dpkg --add-architecture i386 
        sudo mkdir -pm755 /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
        sudo apt update
        sudo apt-cache policy winehq-stable
        sudo apt install --install-recommends winehq-stable
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
        sudo apt install -y ttf-mscorefonts-installer
        sudo fc-cache
        fc-match Arial
        wine --version
        which wine        
      shell: bash
    - name: Install Wine Dependencies for Ubuntu 22.04
      if: runner.os == 'Linux' && steps.osinfo.outputs.version_id == '22.04'
      run: |
        sudo apt clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt update
        sudo apt install p7zip-full curl
        sudo dpkg --add-architecture i386 
        sudo mkdir -pm755 /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
        sudo apt update
        sudo apt-cache policy winehq-stable
        sudo apt install --install-recommends winehq-stable
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
        sudo apt install -y ttf-mscorefonts-installer
        sudo fc-cache
        fc-match Arial
        wine --version
        which wine        
      shell: bash
    - name: Install Dotnet in Wine
      if: runner.os != 'Windows'
      run: |
        wget -qO- https://monogame.net/downloads/net9_mgfxc_wine_setup.sh | bash
      shell: bash
    - name: Setup Environment
      if: runner.os == 'macOS'
      run: echo "WINEPREFIX=/Users/runner/.winemonogame" >> $GITHUB_ENV
      shell: bash
    - name: Setup Environment
      if: runner.os == 'Linux'
      run: echo "WINEPREFIX=/home/runner/.winemonogame" >> $GITHUB_ENV
      shell: bash
    - name: Test Dotnet is installed
      if: runner.os != 'Windows'
      run: |
        echo $GITHUB_ENV
        find ${{ env.WINEPREFIX }} | grep dotnet.exe
        wine dotnet --info
      shell: bash
      env:
        WINEDEBUG: "-all"
