name: 'Install Wine'
description: 'Installs wine on the githib action bot.'
author: 'infspace-studios'
inputs:
  my-input:
    description: 'An example input'
    required: true
runs:
  using: "composite"
  steps:
    - name: Do Step 1
      run: echo "Step 1 with ${{ inputs.my-input }}"
      shell: bash
    - name: Do Step 2
      run: echo "Step 2"
      shell: bash
