name: Install Android Dependencies
description: 'Installs the requested components into the system Android Sdk.'
author: 'infinitespace-studios'
runs:
  using: "composite"
  steps:
    - name: Install Android Dependencies
      if: runner.os != 'Windows'
      run: |
          echo $ANDROID_HOME
          find $ANDROID_HOME | grep sdkmanager
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "platforms;android-35" "platform-tools" "build-tools;34.0.0" "emulator" "system-images;android-34;default;x86_64" "cmdline-tools;11.0"
      shell: bash
    - name: Install Android Dependencies
      if: runner.os == 'Windows'
      run: |
          echo $ANDROID_HOME
          $ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager --version
          $ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager "platforms;android-34" "platforms;android-35" "platform-tools" "build-tools;34.0.0" "emulator" "system-images;android-34;default;x86_64" "cmdline-tools;11.0"
      shell: bash
