name: Install Fonts
description: 'Installs Required MS Fonts on the githib action bot.'
author: 'infinitespace-studios'
runs:
  using: "composite"
  steps:
    - name: Install Fonts
      if: runner.os == 'Linux'
      run: |
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
        sudo apt install -y ttf-mscorefonts-installer
        sudo fc-cache
        fc-match Arial
      shell: bash
