name: Test My Action

on:
  push:
    paths:
      - '**'
      - '.github/workflows/main.yml'

jobs:
  test_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          game_id: '123456'
          channel: 'ubuntu'
          file: 'path/to/game.zip'
          version: '1.0.0'
      - name: check envar works
        run: |
          ${{ env.WINEEXE }} dotnet --info
        shell: bash
  test_linux_22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          game_id: '123456'
          channel: 'ubuntu'
          file: 'path/to/game.zip'
          version: '1.0.0'
      - name: Test Dotnet is installed
        run: |
          ${{ env.WINEEXE }} dotnet.exe --info
        shell: bash
  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          game_id: '123456'
          channel: 'osx'
          file: 'path/to/game.zip'
          version: '1.0.0'
      - name: Test Dotnet is installed
        run: |
          ${{ env.WINEEXE }} dotnet.exe --info
        shell: bash
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          game_id: '123456'
          channel: 'windows'
          file: 'path/to/game.zip'
          version: ${{ github.ref_name }} 
