name: Test My Action

on:
  push:
    paths:
      - '**'
      - '.github/workflows/main.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
