name: Test My Action

on:
  push:
    paths:
      - '**'
      - '.github/workflows/main.yml'

jobs:
  test_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Test Dotnet is installed
        run: |
          find ${{ env.WINEPREFIX }} | grep dotnet.exe
          wine dotnet.exe --info
        shell: bash
  test_linux_22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Test Dotnet is installed
        run: |
          find ${{ env.WINEPREFIX }} | grep dotnet.exe
          wine dotnet.exe --info
        shell: bash
  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Test Dotnet is installed
        run: |
          find ${{ env.WINEPREFIX }} | grep dotnet.exe
          wine dotnet.exe --info
        shell: bash
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
