name: Test My Action

on:
  push:
    paths:
      - '**'
      - '.github/workflows/main.yml'

jobs:
  test_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Test Dotnet is installed
        run: |
          WINEPREFIX=${{ env.WINEPREFIX }} wine where notepad.exe
          WINEPREFIX=${{ env.WINEPREFIX }} winepath C:\
          mkdir -p "${{ env.WINEPREFIX }}/drive_c/pathcheck"
          echo "echo %PATH%" > "${{ env.WINEPREFIX }}/drive_c/windows/showpath.bat"
          WINEPREFIX=${{ env.WINEPREFIX }} wine cmd /c C:\\windows\\showpath.bat
        shell: bash
      - name: check envar works
        run: |
          wine where notepad.exe
          winepath C:\
          wine cmd /c echo %PATH%
        shell: bash
      # - name: Test Dotnet is installed
      #   run: |
      #     WINEPREFIX=${{ env.WINEPREFIX }} wine where dotnet.exe
      #     WINEPREFIX=${{ env.WINEPREFIX }} wine dotnet.exe --info
      #   shell: bash
  test_linux_22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Test Dotnet is installed
        run: |
          find ${{ env.WINEPREFIX }} | grep dotnet.exe
          wine dotnet.exe --info
        shell: bash
  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Test Dotnet is installed
        run: |
          find ${{ env.WINEPREFIX }} | grep dotnet.exe
          wine dotnet.exe --info
        shell: bash
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
