name: Test My Action

on:
  push:
    paths:
      - '**'
      - '.github/workflows/main.yml'

jobs:
  test_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          channel: 'ubuntu'
          file: 'butler.zip'
          version: '1.0.0'
          ITCHIO_USER: ${{ secrets.ITCHIO_USER }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_TOKEN: ${{ secrets.ITCHIO_TOKEN }}
      - name: check envar works
        run: |
          ${{ env.WINEEXE }} dotnet --info
        shell: bash
  test_linux_22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          channel: 'ubuntu'
          file: 'butler.zip'
          version: '1.0.0'
          ITCHIO_USER: ${{ secrets.ITCHIO_USER }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_TOKEN: ${{ secrets.ITCHIO_TOKEN }}
      - name: Test Dotnet is installed
        run: |
          ${{ env.WINEEXE }} dotnet.exe --info
        shell: bash
  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          channel: 'osx'
          file: 'butler.zip'
          version: '1.0.0'
          ITCHIO_USER: ${{ secrets.ITCHIO_USER }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_TOKEN: ${{ secrets.ITCHIO_TOKEN }}
      - name: Test Dotnet is installed
        run: |
          ${{ env.WINEEXE }} dotnet.exe --info
        shell: bash
      - name: check Android SDK
        run: |
          echo $ANDROID_HOME
          find $ANDROID_HOME | grep sdkmanager
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "platforms;android-35" "platform-tools" "build-tools;34.0.0" "emulator" "system-images;android-34;default;x86_64" "cmdline-tools;11.0"
        shell: bash
        
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wine
        uses: ./install-wine
      - name: Install Font
        uses: ./install-fonts
      - name: Publish Game to itch.io
        uses: ./publish-itchio
        with:
          channel: 'windows'
          file: 'butler.zip'
          version: '1.0.0'
          ITCHIO_USER: ${{ secrets.ITCHIO_USER }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_TOKEN: ${{ secrets.ITCHIO_TOKEN }}
